import { Routes } from '@angular/router';
import { HomeComponent } from './pages/home/home.component';
import { BusinessCardsComponent } from './pages/business-cards/business-cards.component';
import { PostcardsPrintAdvertisingComponent } from './pages/postcards-print-advertising/postcards-print-advertising.component';
import { SignsBannersPostersComponent } from './pages/signs-banners-posters/signs-banners-posters.component';
import { LabelsStickersComponent } from './pages/labels-stickers/labels-stickers.component';
import { ClothingBagsComponent } from './pages/clothing-bags/clothing-bags.component';
import { PromotionalProductsComponent } from './pages/promotional-products/promotional-products.component';
import { PackagingComponent } from './pages/packaging/packaging.component';
import { InvitationsGiftsStationeryComponent } from './pages/invitations-gifts-stationery/invitations-gifts-stationery.component';
import { WeddingComponent } from './pages/wedding/wedding.component';
import { DesignServicesComponent } from './pages/design-services/design-services.component';
import { MatteBusinessCardsComponent } from './pages/business-cards/variants/matte-business-cards.component';

export const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'deals', component: HomeComponent },
  { path: 'business-cards', component: BusinessCardsComponent },
  { path: 'business-cards/matte', component: MatteBusinessCardsComponent },
  { path: 'postcards-print-advertising', component: PostcardsPrintAdvertisingComponent },
  { path: 'signs-banners-posters', component: SignsBannersPostersComponent },
  { path: 'labels-stickers', component: LabelsStickersComponent },
  { path: 'clothing-bags', component: ClothingBagsComponent },
  { path: 'promotional-products', component: PromotionalProductsComponent },
  { path: 'packaging', component: PackagingComponent },
  { path: 'invitations-gifts-stationery', component: InvitationsGiftsStationeryComponent },
  { path: 'wedding', component: WeddingComponent },
  { path: 'design-services', component: DesignServicesComponent },
];
